config/routes.rb
Hardy::Application.routes.draw do
  root to: 'sites#index'
  #get 'test_mandrill' => 'sites#test_mandrill'
  #post 'test_mandrill' => 'sites#test_mandrill_send'
  get 'about' => 'sites#about'
  get 'order' => 'sites#mailer-dev.html'
  get 'hardy_research' => 'sites#hardy_research'
  get 'policies' => 'sites#policies'
  get 'checkout' => 'sites#checkout'
  get 'Optimus-DSD' => 'sites#Optimus-DSD'
  match '/admin' => redirect("/admin/root")
  match '/myaccount' => redirect("/myaccount/profile"), as: :myaccount
  get "/contact_us", to: "contacts#show", as: :contact
  post "/contact_us", to: "contacts#create", as: :contact
  resources :faqs, only: [:index]
  resource :email, only: [:create, :destroy] do
    collection do
      get :subscription
      get :unsubscription
    end
  end

  devise_for :clients, controllers: { registrations: "clients/registrations", sessions: "clients/sessions", passwords: "clients/passwords" }
  as :client do
    get 'myaccount/profile' => 'myaccount/profiles#edit', :as => 'edit_client_registration'
    put 'myaccount/profile' => 'myaccount/profiles#update', :as => 'client_registration'
    post 'myaccount/profile' => 'clients/registrations#create'
    get 'clients/user_name/new' => 'clients/user_names#new', as: :new_client_user_name
    post 'clients/user_name' => 'clients/user_names#create', as: :client_user_name
    get 'clients/newsletter' => 'clients/newletters#show', as: :client_newletter
    put 'clients/newsletter' => 'clients/newletters#update', as: :client_newletter
    get 'clients/newsletter/confirmation' => 'clients/newletters#confirmation', as: :confirmation_client_newletter
    get 'clients/pre_order/new' => 'clients/back_ordereds#new', as: :new_client_back_ordered
    get 'clients/pre_order/confirmation' => 'clients/back_ordereds#confirmation', as: :confirmation_client_back_ordered
    post 'clients/pre_order' => 'clients/back_ordereds#create', as: :client_back_ordered
    #put 'clients/back_ordered' => 'clients/back_ordereds#update', as: :client_back_ordered
  end

  devise_for :support_users, controllers: { sessions: "support_users/sessions", passwords: "support_users/passwords" }
  as :support_user do
    get 'admin/profile' => 'admin/profiles#edit', :as => 'edit_user_registration'
    put 'admin/profile' => 'admin/profiles#update', :as => 'user_registration'
  end

  resources :videos, only: [:index, :show] do
    put :disorder_filter, on: :collection
  end
  resources :products, only: [:index, :show] do
    collection do
      put :disorder_filter
      get :search
    end
  end

  resources :countries do
    resources :provinces, only: [:index]
  end

  get '/article/:article_category_permalink/:id', to: 'articles#show', as: :article
  resources :articles, only: [:index] do
    put :disorder_filter, on: :collection
  end

  resources :studies, only: [:index] do
    put :disorder_filter, on: :collection
  end

  resources :addresses, only: [:destroy]

  namespace :myaccount do
    resources :orders, only: [:index, :show]
    resources :payment_profiles, only: :destroy
    resources :pre_orders, only: [:index, :show, :destroy]

    scope module: 'auto_ship' do
      resources :auto_ships, path: "flexible_autoship", only: [:index, :show, :create, :update, :destroy] do
        member do
          put :update_items
          get :invoice
        end
        resources :order_items, only: [:index, :create, :destroy]

        resource :address, only: [:show, :create, :update] do
          member do
            put :select
          end
        end

        member do
          post :generate_order
        end

        resource :shipping_method, only: [:show, :create]

        resource :payment_profile, only: [:show, :create]
      end
    end
  end

  namespace :shopping do
    resource :cart, only: [:show, :update] do
      resources :cart_items, only: [:create, :destroy]
      #TODO: change to post/put
      get :checkout
      get :licence_field
      post :update_price
    end
    resources :addresses do
      put :select, on: :member
    end
    resources :shipping_methods, only: [:index] do
      put :select, on: :collection
    end
    resource :payment, only: [:show, :create]
    resource :guest, only: [:destroy]
    resources :feedbacks, only: [:new, :create]
  end

  namespace :admin do
    match "/root", to: "application#root"
    resources :support_centers
    resources :notes
    resources :emails, only: [:index, :destroy] do
      collection do
        post :export
      end
    end
    resources :support_users do
      resources :commission_rates, except: [:show]
    end

    resources :shipping_promotions, except: [:show]
    resources :product_promotions, except: [:show]
    resources :referral_codes, except: [:show]

    resources :faqs do
      member do
        match :preview, via: [:post, :put]
      end
    end

    resources :products do
      collection do
        get :search
        match "/upload_label_file", to: "products#upload_label_file", via: [:post, :put]
      end
      member do
        match :preview, via: [:post, :put]
      end
    end
    resources :articles do
      collection do
        match "/upload_image", to: "articles#upload_image", via: [:post, :put]
        match "/upload_author_image", to: "articles#upload_author_image", via: [:post, :put]
      end
      member do
        match :preview, via: [:post, :put]
      end
    end
    resources :videos do
      collection do
        match "/upload_image", to: "videos#upload_image", via: [:post, :put]
      end

      member do
        match :preview, via: [:post, :put]
      end
    end

    resources :studies do
      collection do
        match "/upload_journal_cover", to: "studies#upload_journal_cover", via: [:post, :put]
        match "/upload_pdf", to: "studies#upload_pdf", via: [:post, :put]
      end

      member do
        match :preview, via: [:post, :put]
      end
    end

    resources :documents, except: [:show] do
      collection do
        match "/upload_file", to: "documents#upload_file", via: [:post, :put]
      end
    end

    resources :product_images do
      collection do
        match "/upload_image", to: "product_images#upload_image", via: [:post, :put]
      end
    end

    resources :variants, only: :index
    resources :treatments
    resources :clients, except: [:show] do
      member do
        post :select
        post :impersonate
        delete :cancel_select
        put :receive_newletter
      end

      resources :payment_profiles, only: :destroy

      scope module: 'auto_ship' do
        resources :auto_ships, path: "auto_ship", only: [:index, :show, :create, :update, :destroy] do
          member do
            put :update_items
            get :invoice
          end

          resources :auto_ship_adjustments, except: [:index, :show]

          resources :order_items, only: [:index, :create, :destroy]

          resource :address, only: [:show, :create, :update] do
            member do
              put :select
            end
          end

          resource :shipping_method, only: [:show, :create]

          resource :payment_profile, only: [:show, :create]
        end
      end
    end
    resources :orders do
      resources :order_notes
      resource :invoice
      member do
        post :refund_all
      end
      collection do
        get :export_list
        get :invoices
        post :export_shipping_for_canada
        post :export_shipping_for_other_country
        post :ready_all
      end
      member do
        put :update_total
        put :cancel
      end
      resources :order_items do
        member do
          get :new_return
          post :return
        end
      end
      resources :payments do
        member do
          post :void
          get :new_refund
          post :refund
        end
        collection do
          post :pay_by_credit
        end
      end
      resource :shipments do
        collection do
          get :edit_shipping_method
          put :ready
          put :pickup
        end
      end
      resources :shipping_methods do
        put :select, on: :collection
      end
      resources :addresses do
        member do
          put :select
        end
      end
      resources :order_adjustments
    end

    namespace :report do
      resources :sales_and_orders, only: [:index]
      resources :product_sales, only: [:index]
      resources :call_lists, only: [:index]
      resources :auto_ship_reports, only: [:index]
      resources :pre_orders, only: [:index]
      resources :new_customer_pre_orders, only: [:index] do
        collection do
          get :export
        end
      end
      resources :commissions, only: [:index]
      resources :locations, only: [:index] do
        collection do
          get :to_client
          get :back_to
          get :export
        end
      end
    end
    namespace :configuration do
      resource  :country_currency, only: [:show, :create]
      resources :ta_levels, except: [:show]
      resources :introduction_types
      resources :call_frequencies
      resources :country_shipping_adjustments
      resources :registration_methods
      resources :contact_times
      resources :commission_rates, except: [:show]
      resources :disorders
      resources :handling_charges
      #resources :settings
      resource :auto_ship_settings
      resources :transfer_pages, except: [:show]
      resources :global_languages, only: [:index, :create, :destroy]
      resources :limiting_factors, except: [:show]
      resources :diagnoses, except: [:show]
      resources :seos, only: [:index, :edit, :update]
      resources :questions
      resources :age_groups
      resources :genders
      resources :symptoms
      resources :side_effects
      resources :withdrawal_effects
      resources :questionnaires
      resources :user_groups
      resources :drugs
      resources :doctors, only: [:index, :new, :edit]

    end
  end

app/models/order_item.rb
# encoding: utf-8
class OrderItem < ActiveRecord::Base
  include OrderItemExtension
  include Authority::Abilities
  self.authorizer_name = 'OrderItemAuthorizer'
  attr_accessible :order_id, :order, :price, :quantity, :product_id, :caselot_count, :retail_price, :product, :rate, :parent, :pricing_type_id
  belongs_to :product
  belongs_to :order, inverse_of: :order_items
  belongs_to :pricing_type

  belongs_to :parent, class_name: :OrderItem
  has_many :children, class_name: :OrderItem, foreign_key: :parent_id, dependent: :destroy

  validates :quantity, presence: true
  validates_presence_of :product
  #before_validation :change_quantity

  scope :similar_item, lambda{|item| where(product_id: item.product_id, parent_id: nil).first }
  def total
    price * quantity
  end

  def total_for_now
    reload_price * quantity
  end

  def weight
    product.weight_lbs * quantity
  end

  def name
    product.name
  end

  #def change_quantity
    #unless skip_valid_quantity
      #self.quantity = quantity.to_i <= 0 ? 1 : quantity
    #end
  #end

  def reload_price
    self.caselot_count = caselot(order.client).try(:count)
    self.price_for(user: order.client, client: order.currency)
  end

  def can_return_quantity
    quantity + children.where("quantity < ?", 0).sum(&:quantity)
  end
end

app/models/order_item/return_form.rb
class OrderItem::ReturnForm
  include ::NonPersistenceModel

  attr_accessor :quantity, :order_item

  validates_presence_of :quantity
  validates_numericality_of :quantity, greater_than: 0, allow_blank: true
  validate :check_quantity


  def initialize(order_item, attributes = nil)
    @order_item = order_item
    unless attributes.nil?
      @quantity = attributes[:quantity].to_i
    end
  end

  def order
    order_item.order
  end

  def submit?
    ActiveRecord::Base.transaction do
      return false unless valid?
      item = order.order_items.new(quantity: -quantity, product_id: order_item.product_id, price: order_item.price,
                                   pricing_type_id: order_item.pricing_type_id, retail_price: order_item.retail_price, parent: order_item,
                                   caselot_count: order_item.caselot_count)
      item.save
      OrderItemReport.add_report(item)

      order.sync_tax_charge!
      order.change_payment_state!
      order.add_report
      true
    end
  end

  def check_quantity
    if quantity > order_item.can_return_quantity
      errors.add(:base, "Most return #{order_item.can_return_quantity} bottles")
    end
  end
end

app/controllers/admin/auto_ship/order_items_controller.rb
class Admin::AutoShip::OrderItemsController < Admin::AutoShip::BaseController
  include ::AutoShip::OrderItemsC
  def index
    @order_item = AutoShippingItem.new(quantity: 1)
    @products = Product.where(active: true, pre_order: false).default_sort

    render "shared/auto_ship/order_items/index"
  end


  protected
  def update_items_link
    update_items_admin_client_auto_ship_url(client, current_auto_ship)
  end

  def detail_link(order_item)
    admin_client_auto_ship_order_item_url(client, current_auto_ship, order_item)
  end

  def list_link
    admin_client_auto_ship_order_items_url(client, current_auto_ship)
  end

  def address_link
    admin_client_auto_ship_address_url(client, current_auto_ship)
  end

  def search_link
    "/admin/products/search.json"
  end
end

app/controllers/admin/order_items_controller.rb
class Admin::OrderItemsController < Admin::ChangeOrderBaseController
  inherit_resources
  include BaseAdmin
  belongs_to :order
  authorize_actions_for OrderItem, actions: { new_return: :return, return: :return }

  before_filter :state_filter, only: :index

  def index
    @order_item = OrderItem.new(quantity: 1)
    @referral_codes = ReferralCode.all
  end

  def create
    redirect_to [:admin, order], status: 403 and return unless can_create_order_item?
    Product.find(params[:order_item][:product_id])
    order_item = OrderItem.new(params[:order_item])
    order_item.quantity = order_item.quantity == 0 ? 1 : order_item.quantity.abs
    #order_item.pricing_type = order.client.pricing_type
    if order_item.valid?
      order.add_item(order_item)
      @referral_codes = ReferralCode.all
      render partial: "list"
    else
      render text: "something were wrong, please try again", status: 422
    end
  end

  def destroy
    redirect_to [:admin, order], status: 403 and return unless can_destroy_order_item?(resource)
    order.remove_order_item(resource)
    @referral_codes = ReferralCode.all
    render partial: "list"
  end

  def new_return
  #  redirect_to [:admin, order], status: 403 and return unless can_return_order_item?(resource)

    authorize_action_for(resource)
    @return_form = OrderItem::ReturnForm.new(resource)
  end

  def return
  #  redirect_to [:admin, order], status: 403 and return unless can_return_order_item?(resource)
    authorize_action_for(resource)
    @return_form = OrderItem::ReturnForm.new(resource, params[:order_item_return_form])
    if @return_form.submit?
      redirect_to admin_order_order_items_url(order)
    else
      render :new_return
    end
  end

  protected
  def state_filter
    return if order.canceled?
    order.rollback_to_cart unless order.complete?
  end
end

app/controllers/myaccount/auto_ship/order_items_controller.rb
class Myaccount::AutoShip::OrderItemsController < Myaccount::AutoShip::BaseController
  include ::AutoShip::OrderItemsC

  protected
  def update_items_link
    update_items_myaccount_auto_ship_url(current_auto_ship)
  end

  def detail_link(order_item)
    myaccount_auto_ship_order_item_url(current_auto_ship, order_item)
  end

  def list_link
    myaccount_auto_ship_order_items_url(current_auto_ship)
  end

  def address_link
    myaccount_auto_ship_address_url(current_auto_ship)
  end

  def search_link
    "/products/search.json"
  end
end

app/views/admin/order_items/_form.html.erb
<%= form_for [:admin, order, resource] do |f| %>
  <%= render_cell :app, :error_msg, resource: resource %>
  <div>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<%end%>

app/views/admin/order_items/_list.html.erb
<%= form_for [:admin, order] do |f| %>
  <table class="table">
    <thead>
      <tr>
        <th>Item Description</th>
        <th>Price</th>
        <th>Qty</th>
        <th>Caselot Count</th>
        <th>Total</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%= f.fields_for :order_items, f.object.order_items.order(:id) do |s| %>
      <tr class="<%= cycle('odd', 'even')%>">
        <td><%= s.object.product.name %></td>
        <td><%= "#{number_to_currency s.object.price, locale: I18n.default_locale}#{s.object.description_after_price}" %></td>
        <td><%= s.object.quantity %></td>
        <% if can_update_order_item? %>
          <td><%= s.select :caselot_count, s.object.product.product_caselots.for_pricing_type(f.object.pricing_type).order("count").map{|pc| ["#{pc.description}(#{number_to_currency pc.price_for(user: order.client, currency: order.currency, pricing_type: f.object.pricing_type), locale: I18n.default_locale})", pc.count]},
            include_blank: "none(#{number_to_currency s.object.product.price_for(user: order.client, currency: order.currency, pricing_type: f.object.pricing_type), locale: I18n.default_locale})" %></td>
        <% else %>
          <td><%= s.object.caselot_count %></td>
        <% end %>
        <td><%= number_to_currency s.object.total, locale: I18n.default_locale %></td>
        <td class="tableLinks">
          <% if can_destroy_order_item?(s.object) %>
            <%= link_to 'DELETE', [:admin, order, s.object], remote: true, method: :delete, class: "btn delete_item" %>
          <% end %>
          <% if current_support_user.can_return?(s.object) %>
            <%= link_to 'RETURN', new_return_admin_order_order_item_url(order, s.object), class: "btn delete_item" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% if can_create_order_item? %>
  <div>
    <%= f.label :code, "Referral Code" %>
    <%= f.text_field :code, value: f.object.code || f.object.referral_code.try(:code), data: { source: @referral_codes.map(&:code) } %>
  </div>

  <div id="licence_container" data-need-licence="<%= @referral_codes.select(&:need_licence?).map(&:code) %>">
    <%= f.label :licence, "Licence" %>
    <%= f.text_field :licence %>
  </div>
  <% end %>

  <% if can_update_order_item? %>
    <%= f.submit 'Update & Continue', name: "update_and_continue", class: "btn2" %>
    <%= f.submit "Update", class: "btn2" %>
  <% end %>
<% end %>

<script type="text/javascript" charset="utf-8">
var needLicenceArray = $('#licence_container').data("need-licence");
var source = $("#order_code").data("source");

function showOrHideLicence(){
  if($.inArray($("#order_code").val(), needLicenceArray) != -1){
    $('#licence_container').show();
  }else{
    $('#licence_container').hide();
  }
}
$(function(){
  showOrHideLicence();

  $("#order_code").autocomplete({
    source: source,
    close: function( event, ui ) { showOrHideLicence() }
  });

  $('#order_code').keyup(function(){
    showOrHideLicence();
  })
})
</script>

app/views/admin/order_items/index.html.erb
<%= render "admin/orders/nav" %>

<% if can_create_order_item? %>
  <div class="searchProduct">
    <%= form_for [:admin, order, resource], remote: true, html: { id: "add_item_form", class: "orderDate" } do |f| %>
      <label>Name:</label><%= text_field_tag :product_name, nil, id: "search_name", autocomplete: "off", data: { url: "/admin/products/search.json" } %>
      <%= hidden_field_tag :client_id, order.client_id, id: "client_id" %>
      <%= f.hidden_field :product_id, id: "search_id" %>
      <label>Quantity:</label><%= f.text_field :quantity, id: "search_quantity" %>
      <%= f.submit "ADD", class: "search_submit btn2" %>
    <% end %>
  </div>
<% end %>

<div class="order_items_list">
  <%= render 'list' %>
</div>

app/views/admin/order_items/new_return.html.erb
<%= render "admin/orders/nav" %>
<br>
<br>
<%= form_for @return_form, url: return_admin_order_order_item_url(order, @return_form.order_item) do |f| %>
  <h1>Return</h1>
  <%= render_cell :app, :error_msg, resource: @return_form %>
  <%= "Can return #{@return_form.order_item.can_return_quantity} bottles" %>
  <div class="field">
	  <%= f.label :quantity %>
	  <%= f.text_field :quantity %>
	</div>

  <%= f.submit "Return", class: "btn2 flBtn" %>
<% end %>