config/routes.rb
Hardy::Application.routes.draw do
  root to: 'sites#index'
  #get 'test_mandrill' => 'sites#test_mandrill'
  #post 'test_mandrill' => 'sites#test_mandrill_send'
  get 'about' => 'sites#about'
  get 'order' => 'sites#mailer-dev.html'
  get 'hardy_research' => 'sites#hardy_research'
  get 'policies' => 'sites#policies'
  get 'checkout' => 'sites#checkout'
  get 'Optimus-DSD' => 'sites#Optimus-DSD'
  match '/admin' => redirect("/admin/root")
  match '/myaccount' => redirect("/myaccount/profile"), as: :myaccount
  get "/contact_us", to: "contacts#show", as: :contact
  post "/contact_us", to: "contacts#create", as: :contact
  resources :faqs, only: [:index]
  resource :email, only: [:create, :destroy] do
    collection do
      get :subscription
      get :unsubscription
    end
  end

  devise_for :clients, controllers: { registrations: "clients/registrations", sessions: "clients/sessions", passwords: "clients/passwords" }
  as :client do
    get 'myaccount/profile' => 'myaccount/profiles#edit', :as => 'edit_client_registration'
    put 'myaccount/profile' => 'myaccount/profiles#update', :as => 'client_registration'
    post 'myaccount/profile' => 'clients/registrations#create'
    get 'clients/user_name/new' => 'clients/user_names#new', as: :new_client_user_name
    post 'clients/user_name' => 'clients/user_names#create', as: :client_user_name
    get 'clients/newsletter' => 'clients/newletters#show', as: :client_newletter
    put 'clients/newsletter' => 'clients/newletters#update', as: :client_newletter
    get 'clients/newsletter/confirmation' => 'clients/newletters#confirmation', as: :confirmation_client_newletter
    get 'clients/pre_order/new' => 'clients/back_ordereds#new', as: :new_client_back_ordered
    get 'clients/pre_order/confirmation' => 'clients/back_ordereds#confirmation', as: :confirmation_client_back_ordered
    post 'clients/pre_order' => 'clients/back_ordereds#create', as: :client_back_ordered
    #put 'clients/back_ordered' => 'clients/back_ordereds#update', as: :client_back_ordered
  end

  devise_for :support_users, controllers: { sessions: "support_users/sessions", passwords: "support_users/passwords" }
  as :support_user do
    get 'admin/profile' => 'admin/profiles#edit', :as => 'edit_user_registration'
    put 'admin/profile' => 'admin/profiles#update', :as => 'user_registration'
  end

  resources :videos, only: [:index, :show] do
    put :disorder_filter, on: :collection
  end
  resources :products, only: [:index, :show] do
    collection do
      put :disorder_filter
      get :search
    end
  end

  resources :countries do
    resources :provinces, only: [:index]
  end

  get '/article/:article_category_permalink/:id', to: 'articles#show', as: :article
  resources :articles, only: [:index] do
    put :disorder_filter, on: :collection
  end

  resources :studies, only: [:index] do
    put :disorder_filter, on: :collection
  end

  resources :addresses, only: [:destroy]

  namespace :myaccount do
    resources :orders, only: [:index, :show]
    resources :payment_profiles, only: :destroy
    resources :pre_orders, only: [:index, :show, :destroy]

    scope module: 'auto_ship' do
      resources :auto_ships, path: "flexible_autoship", only: [:index, :show, :create, :update, :destroy] do
        member do
          put :update_items
          get :invoice
        end
        resources :order_items, only: [:index, :create, :destroy]

        resource :address, only: [:show, :create, :update] do
          member do
            put :select
          end
        end

        member do
          post :generate_order
        end

        resource :shipping_method, only: [:show, :create]

        resource :payment_profile, only: [:show, :create]
      end
    end
  end

  namespace :shopping do
    resource :cart, only: [:show, :update] do
      resources :cart_items, only: [:create, :destroy]
      #TODO: change to post/put
      get :checkout
      get :licence_field
      post :update_price
    end
    resources :addresses do
      put :select, on: :member
    end
    resources :shipping_methods, only: [:index] do
      put :select, on: :collection
    end
    resource :payment, only: [:show, :create]
    resource :guest, only: [:destroy]
    resources :feedbacks, only: [:new, :create]
  end

  namespace :admin do
    match "/root", to: "application#root"
    resources :support_centers
    resources :notes
    resources :emails, only: [:index, :destroy] do
      collection do
        post :export
      end
    end
    resources :support_users do
      resources :commission_rates, except: [:show]
    end

    resources :shipping_promotions, except: [:show]
    resources :product_promotions, except: [:show]
    resources :referral_codes, except: [:show]

    resources :faqs do
      member do
        match :preview, via: [:post, :put]
      end
    end

    resources :products do
      collection do
        get :search
        match "/upload_label_file", to: "products#upload_label_file", via: [:post, :put]
      end
      member do
        match :preview, via: [:post, :put]
      end
    end
    resources :articles do
      collection do
        match "/upload_image", to: "articles#upload_image", via: [:post, :put]
        match "/upload_author_image", to: "articles#upload_author_image", via: [:post, :put]
      end
      member do
        match :preview, via: [:post, :put]
      end
    end
    resources :videos do
      collection do
        match "/upload_image", to: "videos#upload_image", via: [:post, :put]
      end

      member do
        match :preview, via: [:post, :put]
      end
    end

    resources :studies do
      collection do
        match "/upload_journal_cover", to: "studies#upload_journal_cover", via: [:post, :put]
        match "/upload_pdf", to: "studies#upload_pdf", via: [:post, :put]
      end

      member do
        match :preview, via: [:post, :put]
      end
    end

    resources :documents, except: [:show] do
      collection do
        match "/upload_file", to: "documents#upload_file", via: [:post, :put]
      end
    end

    resources :product_images do
      collection do
        match "/upload_image", to: "product_images#upload_image", via: [:post, :put]
      end
    end

    resources :variants, only: :index
    resources :treatments
    resources :clients, except: [:show] do
      member do
        post :select
        post :impersonate
        delete :cancel_select
        put :receive_newletter
      end

      resources :payment_profiles, only: :destroy

      scope module: 'auto_ship' do
        resources :auto_ships, path: "auto_ship", only: [:index, :show, :create, :update, :destroy] do
          member do
            put :update_items
            get :invoice
          end

          resources :auto_ship_adjustments, except: [:index, :show]

          resources :order_items, only: [:index, :create, :destroy]

          resource :address, only: [:show, :create, :update] do
            member do
              put :select
            end
          end

          resource :shipping_method, only: [:show, :create]

          resource :payment_profile, only: [:show, :create]
        end
      end
    end
    resources :orders do
      resources :order_notes
      resource :invoice
      member do
        post :refund_all
      end
      collection do
        get :export_list
        get :invoices
        post :export_shipping_for_canada
        post :export_shipping_for_other_country
        post :ready_all
      end
      member do
        put :update_total
        put :cancel
      end
      resources :order_items do
        member do
          get :new_return
          post :return
        end
      end
      resources :payments do
        member do
          post :void
          get :new_refund
          post :refund
        end
        collection do
          post :pay_by_credit
        end
      end
      resource :shipments do
        collection do
          get :edit_shipping_method
          put :ready
          put :pickup
        end
      end
      resources :shipping_methods do
        put :select, on: :collection
      end
      resources :addresses do
        member do
          put :select
        end
      end
      resources :order_adjustments
    end

    namespace :report do
      resources :sales_and_orders, only: [:index]
      resources :product_sales, only: [:index]
      resources :call_lists, only: [:index]
      resources :auto_ship_reports, only: [:index]
      resources :pre_orders, only: [:index]
      resources :new_customer_pre_orders, only: [:index] do
        collection do
          get :export
        end
      end
      resources :commissions, only: [:index]
      resources :locations, only: [:index] do
        collection do
          get :to_client
          get :back_to
          get :export
        end
      end
    end
    namespace :configuration do
      resource  :country_currency, only: [:show, :create]
      resources :ta_levels, except: [:show]
      resources :introduction_types
      resources :call_frequencies
      resources :country_shipping_adjustments
      resources :registration_methods
      resources :contact_times
      resources :commission_rates, except: [:show]
      resources :disorders
      resources :handling_charges
      #resources :settings
      resource :auto_ship_settings
      resources :transfer_pages, except: [:show]
      resources :global_languages, only: [:index, :create, :destroy]
      resources :limiting_factors, except: [:show]
      resources :diagnoses, except: [:show]
      resources :seos, only: [:index, :edit, :update]
      resources :questions
      resources :age_groups
      resources :genders
      resources :symptoms
      resources :side_effects
      resources :withdrawal_effects
      resources :questionnaires
      resources :user_groups
      resources :drugs
      resources :doctors, only: [:index, :new, :edit]

    end
  end

app/models/client.rb
class Client < ActiveRecord::Base
  include Authority::Abilities
  include Authority::UserAbilities
  self.authorizer_name = 'ClientAuthorizer'


  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:user_name], reset_password_keys: [:user_name, :email]

  attr_accessor :receive_update, :back_end

  validates_format_of :email, allow_blank: true, with: email_regexp
  validates_uniqueness_of :user_name
  validates_presence_of :user_name, :first_name, :last_name, :country
  validates_presence_of :support_center, if: proc {|client| client.check_support_center }
  validates_presence_of :email, if: proc {|client| client.receive_update == "1" }

  validates_presence_of :address_1, :city, :province, :country_id, :postal_code, if: proc {|client| client.check_support_center }
  validates_length_of :home_phone, in: 7..32, if: proc {|client| client.check_home_phone }
  validate :check_introduction_type

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_name, :first_name, :middle_name, :last_name, :country_id, :country,
    :date_of_birth, :gender, :guardian, :active, :address_1, :address_2, :address_3, :city, :province, :postal_code,
    :home_phone, :work_phone, :cell_phone, :pager, :fax, :work_email, :contact_day, :contact_time_id, :time_zone, :introduction_type_id,
    :register_method_id, :general_comments, :main_participant, :call_frequency_id, :mental_wellness, :mental_wellness_details, :pricing_type_id, :support_user_id,
    :support_center_id, :language_id, :currency_id, :quit_reason_id, :age_category_id, :support_center, :contact_date, :deleted, :guest, :ta_level_id, :ta_comments, :next_contact_date,
    :receive_update, :limiting_factor_ids, :diagnosis_ids, :back_ordered_customer

  attr_accessor :check_support_center, :checkout_address, :check_home_phone

  has_one :cart, as: :shopper, dependent: :destroy
  has_many :payment_profiles#, dependent: :destroy
  has_many :addresses
  has_many :orders, dependent: :restrict
  has_many :pre_orders, through: :orders
  has_many :payments, through: :orders
  has_many :notes, dependent: :destroy
  has_many :order_notes, dependent: :destroy
  has_many :auto_shippings
  has_many :client_limiting_factors, dependent: :destroy
  has_many :limiting_factors, through: :client_limiting_factors
  accepts_nested_attributes_for :limiting_factors, allow_destroy: true

  has_many :client_diagnoses, dependent: :destroy
  has_many :diagnoses, through: :client_diagnoses
  accepts_nested_attributes_for :diagnoses, allow_destroy: true

  has_many :view_client_reports, dependent: :destroy

  belongs_to :support_center
  belongs_to :currency
  belongs_to :country
  belongs_to :pricing_type
  belongs_to :support_user
  belongs_to :contact_time
  belongs_to :introduction_type
  belongs_to :registration_method, foreign_key: :register_method_id
  belongs_to :call_frequency
  belongs_to :language
  belongs_to :quit_reason
  belongs_to :age_category
  belongs_to :ta_level

  after_create :send_welcome_email
  before_create :set_currency
  before_save :set_pricing_type
  #before_create :set_support_center
  #before_update :set_news_letter

  def submit?(options = {})
    transaction do
      options.reverse_merge!({generate_address: false})
      if save
        if options[:generate_address]
          addresses.create(name: full_name, address1: address_1, address2: address_2, city: city, state: province, country_id: country_id, postal_code: postal_code, active: true, phone: home_phone)
        end

        if receive_update == "1" && Email.where("lower(email) = ?", email.try(:downcase)).empty?
          Email.subscribe(self)
        elsif receive_update != "1"
          Email.unsubscribe(self)
        end

        true
      else
        false
      end
    end
  end

  def receive_update
    @receive_update ||=  if email.blank?
                           "0"
                         elsif Email.where("lower(email) = ?", email.downcase).any?
                           "1"
                         elsif MailChimp.exist_subscriber?(self)
                           "1"
                         else
                           "0"
                         end
  end

  def receive_update?
    receive_update == "1"
  end

  def is_guest?
    guest
  end

  #new first_last_name
  def full_name
    str = "#{first_name} #{last_name}"
    str += " - Guest" if guest?
    str
  end

  def first_last_name
    "#{first_name} #{last_name}"
  end

  #def self.find_for_database_authentication(conditions={})
  #self.where("user_name = ?", conditions[:user_name]).limit(1).first ||
  #self.where("email = ?", conditions[:user_name]).limit(1).first
  #end

  def set_currency
    self.currency = self.country.name == "Canada" ? Currency.find_by_name("CAD") : Currency.find_by_name("USD")
  end

  def currency!
    currency || Currency.find_by_id(currency_id!)
  end

  def currency_id!
    currency_id || country.currency_id
  end

  #def set_support_center
  #self.support_center_id = SupportCenter.find_by_default(true).try(:id) unless self.support_center.present?
  #end

  def commissioned_orders
    orders.where(state: 'complete', payment_state: 'paid').order('completed_at')
  end

  def commission_calculated_orders(from_date, to_date)
    if support_user.commission_by_amount?
      orders_with_commission_calculated_by_amount(from_date, to_date)
    else
      orders_with_commission_calculated_by_order(from_date, to_date)
    end
  end

  def orders_with_commission_calculated_by_amount(from_date, to_date)
    result_orders=[]
    earlier_total = 0
    commissioned_orders.each do |order|
      order.calculate_commission_by_amount(earlier_total, support_user.commission_rates_by_type(CommissionType::AMOUNT))
      earlier_total += order.total
      result_orders.unshift(order) if order.completed_between?(from_date, to_date)
    end
    result_orders
  end

  def orders_with_commission_calculated_by_order(from_date, to_date)
    result_orders=[]
    commissioned_orders.each_with_index do |order, index|
      order.calculate_commission_by_number(index+1, support_user.commission_rates_by_type(CommissionType::NUMBER))
      result_orders.unshift(order) if order.completed_between?(from_date, to_date)
    end
    result_orders
  end

  def email_changed?;  false; end
  def email_required?;  false; end

  def credit_amount
    payments.where(payment_type_id:  PaymentType.credit_type.id, received: true).sum(&:amount).abs
  end

  def has_credit?
    credit_amount > 0
  end

  def email_or_default
    email.present? ? email : "noemail@gethardy.com"
  end

  private
  def send_welcome_email
    return unless self.password
    NotificationMailer.client_signup(self).deliver
  end

  def set_pricing_type
    return unless pricing_type.nil?
    self.pricing_type = PricingType.find_by_name("Retail")
  end

  def check_introduction_type
    if introduction_type.blank?
      if back_end
        validates_presence_of :introduction_type
      else
        errors.add(:base, "Please let us know how you heard about us so we can serve you better.")
      end
    end
  end

  #def set_news_letter
  #if receive_update == "1" && changed.include?("email")
  #if Client.where(email: email_change[0]).count == 1
  ##Email.find_by_email(email_change[0]).try(:destroy)
  #MailChimp.unsubscribe(Client.new(email: email_change[0]))
  #end
  #end
  #end
end

app/models/old/order.rb
class Order < ActiveRecord::Base
end

app/controllers/myaccount/orders_controller.rb
class Myaccount::OrdersController < Myaccount::BaseController
  def index
    @orders = current_client.orders.where(state: "complete").order("completed_at desc").page(params[:page]).per(BASE_CONFIG[:page])
  end

  def show
    @order = current_client.orders.find(params[:id])
  end
end

app/views/admin/orders/_canada_export_list.html.erb
<div class="nonprinting">
  <h2>Canadian Orders</h2>
  <br />
  <%= link_to '[Orders ready for shipping]', export_list_admin_orders_url(q: { shipment_address_country_abbr_in: ["CA", "AU", "NZ"] + Country::EUROPEAN_UNION }) %>
  <%= link_to '[Shipped orders]', export_list_admin_orders_url(q: { shipment_state_eq: "shipped", shipment_address_country_abbr_in: ["CA", "AU", "NZ"] + Country::EUROPEAN_UNION }) %>
  <br />
  <%= form_tag export_shipping_for_canada_admin_orders_url, data: { export_order: "" } do %>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Package Number</th>
        <%= sortable Order, 'id', "Order ID" %>
        <%= sortable Client, 'first_name', "Client Name" %>
        <th>Product Quantity</th>
        <% if params[:q].try(:[], :shipment_state_eq) == "shipped"  %>
        <%= sortable Shipment, 'shipped_at' %>
        <% end %>
        <%= sortable Order, 'completed_at' %>
      </tr>
    </thead>
    <tbody>
    <% orders.each do |order| %>
      <tr  class="<%= cycle('odd', 'even')%>">
        <td><%= check_box_tag "order[#{order.id}][id]", order.id, !order.shipment.shipped? %></td>
        <% if order.shipment.shipped? %>
        <td><%= order.package_number %></td>
        <% else %>
        <td><%= text_field_tag "order[#{order.id}][package_number]", order.package_number || 1 %></td>
        <% end %>
        <td><%= order.id %></td>
        <td><%= order.client.full_name %></td>
        <td><%= order.quantity %></td>
        <% if params[:q].try(:[], :shipment_state_eq) == "shipped"  %>
          <td><%= order.shipment.format_shipped_at %></td>
        <% end %>
        <td><%= order.format_completed_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="buttons">
    <% if orders.any? %>
      <%= submit_tag "Export Order", name: "export", class: "btn2 flBtn" %>
      <%= submit_tag "Export Order Like US/International", name: "export_like_us", class: "btn2 flBtn" %>
      <%= link_to 'print', invoices_admin_orders_url, data: { print_invoice: "" }, class: "button" %>
      <% if params[:q].try(:[], :shipment_state_eq) != "shipped" %>
        <%= submit_tag "Ship Order", class: "btn2", confirm: "Are you sure you want to ship the orders?" %>
      <% end %>
    <% end %>
  </div>

<% end %>
<br />

<%= paginate @orders %>
</div>
<div class="printInvoiceCont" data-invoices >
</div>

app/views/admin/orders/_nav.html.erb
<div class="subNav">
	<div class="status">
      	Order ID: <span>[ <%= order.id %> ]</span>
      	Order State: <span>[ <%= order.state %> ]</span>
      	Payment State: <span>[ <%= "#{order.payment_state_title} #{show_need_total(order)}" %> ]</span>

      	<% if order.shipment %>
			Shipment State: <span>[ <%= order.shipment.state %> ]</span>
      	<% end %>
      	Order Type: <span>[ <%= order.order_type.name %> ]</span>
        <%# unless order.canceled?  %>
        <% if current_support_user.can_cancel? order %>
          <%= link_to 'Cancel Order', cancel_admin_order_url(order), method: :put %>
        <% end %>
  	</div>
  	<ul>
		<li class=<%=active_nav("orders")%>><%= link_to 'Overview', [:admin, order] %></li>
		<li class=<%=active_nav("order_items")%>><span class="cutOffRule">|</span><%= link_to 'Products', admin_order_order_items_url(order) %></li>
		<li class=<%=active_nav("shipments")%>><span class="cutOffRule">|</span><%= link_to 'Shipments', admin_order_shipments_url(order) %></li>
		<% if current_support_user.can_read? OrderAdjustment %>
		  <li class=<%=active_nav("order_adjustments")%>><span class="cutOffRule">|</span><%= link_to 'Adjustments', admin_order_order_adjustments_url(order) %></li>
		<% end %>
		<% if current_support_user.can_read? Payment %>
		  <li class=<%=active_nav("payments")%>><span class="cutOffRule">|</span><%= link_to 'Payments', admin_order_payments_url(order) %></li>
		<% end %>
		<% if current_support_user.can_read? OrderNote %>
		  <li class=<%=active_nav("order_notes")%>><span class="cutOffRule">|</span><%= link_to 'Order Notes', admin_order_order_notes_url(order) %></li>
		<% end %>
		<li class=<%=active_nav("invoices")%>><span class="cutOffRule">|</span><%= link_to 'Invoice', admin_order_invoice_url(order) %></li>
  	</ul>
  	<% if order.payments.any? || order.canceled? %>
   		Currency [<%= order.currency.name %>]
		<% else %>
			<%= form_for [:admin, order] do |f| %>
			<label>Currency:</label> <%= f.select :currency_id, Currency.all.map{|c| [c.name, c.id]}, {selected: order.currency_id}, :class => "selectbox" %>
			<%= f.submit value: 'Update Currency', class:"btn2 updateOrder" %>
		<% end %>
	<% end %>
  
  	
  	<br />
  	
</div>

app/views/admin/orders/export_list.html.erb
<%= stylesheet_link_tag "invoice_print.css", media: "print" %>

<div class="nonprinting">	
	<%= link_to '[Canadian Orders]', export_list_admin_orders_url(q: { shipment_address_country_abbr_in: ["CA", "AU", "NZ"] + Country::EUROPEAN_UNION }) %>
	<%= link_to '[US/International Orders]', export_list_admin_orders_url %>
</div>
<% if params[:q].try(:[], :shipment_address_country_abbr_in) %>
  <%= render 'canada_export_list', orders: @orders %>
<% else %>
  <%= render 'other_country_export_list', orders: @orders %>
<% end %>

app/views/admin/orders/index.html.erb
<div class="orderFilter">
  <%= form_for @search_order, as: "q", url: admin_orders_url, method: :get do |f| %>
  <div class="col firstcol">
    <div class="field">
      <%= f.label :id_eq, "Order ID" %>
      <%= f.text_field :id_eq %>
    </div>

    <div class="field">
      <%= f.label :client_email_or_client_first_name_or_client_last_name_or_client_user_name_cont, "Key Word" %>
      <%= f.text_field :client_email_or_client_first_name_or_client_last_name_or_client_user_name_cont %>
    </div>
  </div>
  <div class="col">
    <div class="field">
      <%= f.label :client_first_name_cont, "First Name" %>
      <%= f.text_field :client_first_name_cont %>
    </div>
    <div class="field">
      <%= f.label :client_last_name_cont, "Last Name" %>
      <%= f.text_field :client_last_name_cont %>
    </div>
  </div>
  <div class="col">
    <div class="field">
      <%= f.label :client_email_cont, "Email" %>
      <%= f.text_field :client_email_cont %>
    </div>
    <div class="field">
      <%= f.label :client_home_phone_or_client_work_phone_or_client_cell_phone_cont, "Phone Number" %>
      <%= f.text_field :client_home_phone_or_client_work_phone_or_client_cell_phone_cont %>
    </div>
  </div>
  <div class="radioField">
    <div class="field">
      <% Search::Order::COUNTRY_VALUE.each do |k, v| %>
        <%= f.label "shipment_address_country_abbr_eq_#{v.downcase}" do %>
          <%= k.to_s.titleize %>
          <%= f.radio_button :shipment_address_country_abbr_eq, v %>
        <% end %>
      <% end %>
    </div>

    <div class="field">
      <% Search::Order::STATE_VALUE.keys.each do |k| %>
        <%= f.label "state_value_#{k.to_s}" do %>
          <%= k.to_s.titleize %>
          <%= f.radio_button :state_value, k %>
        <% end %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :only_balance do %>
        <%= f.check_box :only_balance %>
      Only Balance
    <% end %>
      <%= f.label :only_pending do %>
        <%= f.check_box :only_pending %>
      Only Pending
    <% end %>
    </div>
  </div>
  <div class="filterDateWrap">
     <div class="filterDate">
        <label>From:</label> <%= f.date_select :completed_at_gteq, { start_year: 2013, end_year: Time.zone.now.year }, class: "selectbox" %>
      <label>To:</label> <%= f.date_select :completed_at_lteq, { start_year: 2013, end_year: Time.zone.now.year }, class: "selectbox" %>
      </div>
      <%= f.submit "Search", class: "btn2" %>
  </div>
  <% end %>
</div>

  <% if current_client && current_support_user.can_create?(Order) %>
   <p class="row"> <%= link_to "Create New Order", admin_orders_url, method: :post, class: "btn2" %><p>
  <% end %>
<%= form_tag ready_all_admin_orders_url do %>
  <% if current_support_user.can_ready? Order %>
  	<div id="select-all">
		<%= label_tag :select_all_orders do %>
		  Select All<%= check_box_tag :select_all_orders, "", false, id: "select_all_orders" %>
		<% end %>
		<%= submit_tag "SHIP ORDERS", class: "btn2", name: "ready" %>
		<%= submit_tag "CANCEL SHIP ORDERS", class: "btn2"%>
    </div>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <%= sortable Order, 'id', "ID" %>
        <%= sortable Order, 'client_id', "Client Name" %>
        <%= sortable Order, 'state' %>
        <%= sortable Order, 'payment_state' %>
        <%= sortable Order, 'balance' %>
        <%= sortable Shipment, 'state', "Shipment State" %>
        <%= sortable Order, 'completed_at' %>
        <% unless hide_total_column?(@search_order) %>
          <th>Total</th>
        <% end %>
        <th></th>
        <th>
        <% unless hide_total_column?(@search_order) %>
          <%= number_to_currency @orders.sum(&:total!), locale: I18n.default_locale %>
        <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
    <tr  class="<%= cycle('odd', 'even')%>">
      <td><%= order.id %></td>
      <td><%= order.client.full_name %></td>
      <td><%= order.state %></td>
      <td><%= order.payment_state_title %></td>
      <td><%= number_to_currency order.balance_amount, locale: I18n.default_locale %></td>
      <td><%= order.shipment.try(:state) %></td>
      <td><%= order.format_completed_at %></td>
      <% unless hide_total_column?(@search_order) %>
        <td><%= number_to_currency order.total!, locale: I18n.default_locale %></td>
      <% end %>
      <td>
        <% if current_support_user.can_ready?(order) || current_support_user.can_pending?(order) %>
          <%= check_box_tag "order_ids[]", order.id, false, class: "order_ids" %>
        <% end %>
      </td>
      <td class="tableLinks"><%= link_to "View", [:admin, order] %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>


<%= paginate @orders %>